import os
from fpdf import FPDF
from datetime import datetime, UTC
from typing import Any
from pathlib import Path

from app.db import (
    get_consultation, 
    get_user_by_id, 
    get_lawyer, 
    create_document,
    get_payment,
)
from app.settings import UPLOADS_DIR

class EngagementLetterPDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 16)
        self.cell(0, 10, "PROVISIONAL ENGAGEMENT LETTER", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, "Pursuant to the NBA Rules of Professional Conduct", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Nigeria Legal Marketplace", align="C")


class TaxReceiptPDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 20)
        self.cell(0, 15, "OFFICIAL TAX RECEIPT", border=0, align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("helvetica", "", 10)
        self.cell(0, 8, "Nigeria Legal Marketplace Limited", border=0, align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 8, "TIN: 23145678-0001 (FIRS Registered)", border=0, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, "This is a computer-generated tax receipt. Valid for FIRS VAT deduction.", align="C")

async def generate_engagement_letter(consultation_id: int) -> dict[str, Any] | None:
    """Generate a PDF engagement letter for a consultation.
    """
    cons = await get_consultation(consultation_id)
    if not cons:
        return None
    
    client = await get_user_by_id(cons["client_user_id"])
    lawyer = await get_lawyer(cons["lawyer_id"])
    
    if not client or not lawyer:
        return None
        
    pdf = EngagementLetterPDF()
    pdf.add_page()
    
    # Date and Ref
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 10, f"Date: {datetime.now(UTC).strftime('%d %B %Y')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, f"Ref: NLM-CONS-{consultation_id}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    # Parties
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 10, "BETWEEN:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 7, f"1. {client['full_name']} (hereinafter referred to as the 'Client')\nAND\n2. {lawyer['full_name']} (hereinafter referred to as the 'Legal Practitioner')")
    pdf.ln(3)

    # Lawyer credentials (NBA RPC Rule 10 mandatory fields)
    pdf.set_font("helvetica", "I", 9)
    enrollment = lawyer.get("enrollment_number") or getattr(lawyer, "enrollment_number", None) or "Pending Verification"
    bar_chapter = lawyer.get("bar_chapter") or getattr(lawyer, "bar_chapter", None) or "Not specified"
    pdf.cell(0, 7, f"NBA Enrollment No: {enrollment}    Bar Chapter: {bar_chapter}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.ln(5)
    
    # Scope
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 10, "1. SCOPE OF ENGAGEMENT", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 7, f"The Client hereby engages the Legal Practitioner for a consultation scheduled for {cons['scheduled_for']} regarding the following matter:\n\n{cons['summary']}")
    pdf.ln(5)
    
    # Fees
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 10, "2. FINANCIAL TERMS", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    
    if cons.get("is_contingency"):
        percentage = cons.get("contingency_percentage", 10)
        pdf.multi_cell(0, 7, f"This is a success-based engagement (Contingency Fee). The Legal Practitioner shall be entitled to {percentage}% of any funds recovered, plus 7.5% FIRS VAT. Any initial consultation fee is separate.")
        pdf.ln(2)
        pdf.set_font("helvetica", "BI", 10)
        pdf.multi_cell(0, 7, "LIEN CLAUSE: Pursuant to standard legal practice, the Legal Practitioner shall have a lien on all recovered funds until the success fee is settled through the platform.")
        pdf.set_font("helvetica", "", 10)
    elif lawyer["base_consult_fee_ngn"] == 0:
        pdf.multi_cell(0, 7, "This is a PRO BONO engagement. The Legal Practitioner provides their services free of charge for this specific matter as part of their social impact commitment.")
    else:
        pdf.multi_cell(0, 7, f"The base consultation fee is NGN {lawyer['base_consult_fee_ngn']:,}. This fee is payable via the Nigeria Legal Marketplace platform prior to the commencement of the consultation.")
    pdf.ln(5)
    
    # Compliance
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 10, "3. PROFESSIONAL STANDARDS", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 7, "This engagement is subject to the Rules of Professional Conduct for Legal Practitioners in Nigeria. The Legal Practitioner confirms they have conducted a preliminary conflict-of-interest check based on the information provided.")
    pdf.ln(10)
    
    # Signatures (Placeholders)
    pdf.cell(90, 10, "__________________________", border=0)
    pdf.cell(90, 10, "__________________________", border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.cell(90, 10, "For: The Client", border=0)
    pdf.cell(90, 10, "For: The Legal Practitioner", border=0)
    
    # Save file
    filename = f"engagement_letter_{consultation_id}.pdf"
    storage_key = f"cons_{consultation_id}/engagement_{int(datetime.now(UTC).timestamp())}.pdf"
    
    # Ensure directory exists in uploads
    # In our simplified logic, storage_key might just be a filename in UPLOADS_DIR
    target_path = UPLOADS_DIR / storage_key
    target_path.parent.mkdir(parents=True, exist_ok=True)
    
    pdf.output(str(target_path))
    
    # Register as a document in the DB
    # Attribute to the client who booked the consultation
    system_user_id = cons["client_user_id"]
    doc = await create_document(
        consultation_id=consultation_id,
        uploaded_by_user_id=system_user_id,
        document_label="Engagement Letter",
        original_filename=filename,
        content_type="application/pdf",
        file_bytes=target_path.read_bytes()
    )
    
    return doc


async def generate_tax_receipt(payment_id: int) -> dict[str, Any] | None:
    """Generate a FIRS-compliant VAT receipt for a payment."""
    payment = await get_payment(payment_id)
    if not payment or payment["status"] != "paid":
        return None
    
    cons = await get_consultation(payment["consultation_id"])
    client = await get_user_by_id(cons["client_user_id"])
    lawyer = await get_lawyer(cons["lawyer_id"])
    
    pdf = TaxReceiptPDF()
    pdf.add_page()
    
    # Receipt Meta
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 10, f"Receipt No: {payment['reference']}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, f"Date: {datetime.now(UTC).strftime('%d %B %Y')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    # Billed To
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "BILLED TO:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 7, f"Client Name: {client['full_name']}\nCase Ref: NLM-CONS-{cons['id']}")
    pdf.ln(10)
    
    # Itemized Table
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(100, 10, "Description", border=1)
    pdf.cell(60, 10, "Amount (NGN)", border=1, new_x="LMARGIN", new_y="NEXT", align="R")
    
    pdf.set_font("helvetica", "", 10)
    desc = f"Legal Consultation (Lawyer: {lawyer['full_name']})"
    if cons.get("is_contingency"):
        desc = f"Success Fee (Case Recovery - {cons.get('contingency_percentage')}% Share)"
    
    pdf.cell(100, 10, desc, border=1)
    pdf.cell(60, 10, f"{payment['amount_ngn']:,}.00", border=1, new_x="LMARGIN", new_y="NEXT", align="R")
    
    # VAT Line
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(100, 10, "VAT (7.5%)", border=1)
    pdf.cell(60, 10, f"{payment['vat_amount_ngn']:,}.00", border=1, new_x="LMARGIN", new_y="NEXT", align="R")
    
    # Total
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(100, 12, "TOTAL PAID", border=1, fill=True)
    pdf.cell(60, 12, f"NGN {payment['total_plus_vat_ngn']:,}.00", border=1, new_x="LMARGIN", new_y="NEXT", align="R", fill=True)
    
    pdf.ln(20)
    pdf.set_font("helvetica", "I", 9)
    pdf.multi_cell(0, 7, "Thank you for using Nigeria Legal Marketplace. Professional legal services are core to the rule of law. We appreciate your prompt payment.")
    
    # Save file
    storage_key = f"cons_{cons['id']}/receipt_{payment['reference']}.pdf"
    target_path = UPLOADS_DIR / storage_key
    target_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(target_path))
    
    # Register doc — attribute to the client who owns the consultation
    system_user_id = cons["client_user_id"]
    return await create_document(
        consultation_id=cons["id"],
        uploaded_by_user_id=system_user_id,
        document_label="Tax Receipt",
        original_filename=f"Receipt_{payment['reference']}.pdf",
        content_type="application/pdf",
        file_bytes=target_path.read_bytes()
    )
