import os
from fpdf import FPDF
from datetime import datetime, UTC
from typing import Any
from pathlib import Path

from app.db import get_consultation, get_user_by_id, get_lawyer, create_document
from app.settings import UPLOADS_DIR

class EngagementLetterPDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 16)
        self.cell(0, 10, "PROVISIONAL ENGAGEMENT LETTER", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, "Pursuant to the NBA Rules of Professional Conduct", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Nigeria Legal Marketplace", align="C")

async def generate_engagement_letter(consultation_id: int) -> dict[str, Any] | None:
    """Generate a PDF engagement letter for a consultation.
    """
    cons = await get_consultation(consultation_id)
    if not cons:
        return None
    
    client = await get_user_by_id(cons["client_user_id"])
    lawyer = await get_lawyer(cons["lawyer_id"])
    
    if not client or not lawyer:
        return None
        
    pdf = EngagementLetterPDF()
    pdf.add_page()
    
    # Date and Ref
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 10, f"Date: {datetime.now(UTC).strftime('%d %B %Y')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, f"Ref: NLM-CONS-{consultation_id}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    # Parties
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 10, "BETWEEN:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 7, f"1. {client['full_name']} (hereinafter referred to as the 'Client')\nAND\n2. {lawyer['full_name']} (hereinafter referred to as the 'Legal Practitioner')")
    pdf.ln(5)
    
    # Scope
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 10, "1. SCOPE OF ENGAGEMENT", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 7, f"The Client hereby engages the Legal Practitioner for a consultation scheduled for {cons['scheduled_for']} regarding the following matter:\n\n{cons['summary']}")
    pdf.ln(5)
    
    # Fees
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 10, "2. FINANCIAL TERMS", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 7, f"The base consultation fee is NGN {lawyer['base_consult_fee_ngn']:,}. This fee is payable via the Nigeria Legal Marketplace platform prior to the commencement of the consultation.")
    pdf.ln(5)
    
    # Compliance
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 10, "3. PROFESSIONAL STANDARDS", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 7, "This engagement is subject to the Rules of Professional Conduct for Legal Practitioners in Nigeria. The Legal Practitioner confirms they have conducted a preliminary conflict-of-interest check based on the information provided.")
    pdf.ln(10)
    
    # Signatures (Placeholders)
    pdf.cell(90, 10, "__________________________", border=0)
    pdf.cell(90, 10, "__________________________", border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.cell(90, 10, "For: The Client", border=0)
    pdf.cell(90, 10, "For: The Legal Practitioner", border=0)
    
    # Save file
    filename = f"engagement_letter_{consultation_id}.pdf"
    storage_key = f"cons_{consultation_id}/engagement_{int(datetime.now(UTC).timestamp())}.pdf"
    
    # Ensure directory exists in uploads
    # In our simplified logic, storage_key might just be a filename in UPLOADS_DIR
    target_path = UPLOADS_DIR / storage_key
    target_path.parent.mkdir(parents=True, exist_ok=True)
    
    pdf.output(str(target_path))
    
    # Register as a document in the DB
    # We'll use the lawyer/admin as the 'uploaded_by' ID (simplified to 1 for system)
    doc = await create_document(
        consultation_id=consultation_id,
        uploaded_by_user_id=1, # System/Admin
        document_label="Engagement Letter",
        original_filename=filename,
        content_type="application/pdf",
        file_bytes=target_path.read_bytes()
    )
    
    return doc
