from __future__ import annotations

from app.models import Lawyer


SEED_LAWYERS = [
    Lawyer(
        id="lw_001",
        full_name="Amaka Okonkwo",
        state="Lagos",
        practice_areas=["employment", "contracts"],
        years_called=8,
        nin_verified=True,
        nba_verified=True,
        bvn_verified=True,
        profile_completeness=92,
        completed_matters=37,
        rating=4.8,
        response_rate=96,
        avg_response_hours=1.8,
        repeat_client_rate=41,
        base_consult_fee_ngn=45000,
        active_complaints=0,
        court_admissions=["state_high_court", "national_industrial"],
        legal_system="common_law",
        pro_bono_practice_areas=["employment"],
    ),
    Lawyer(
        id="lw_002",
        full_name="Ibrahim Yusuf SAN",
        state="Abuja",
        practice_areas=["property", "litigation"],
        years_called=14,
        nin_verified=True,
        nba_verified=True,
        bvn_verified=True,
        profile_completeness=88,
        completed_matters=52,
        rating=4.7,
        response_rate=93,
        avg_response_hours=3.5,
        repeat_client_rate=34,
        base_consult_fee_ngn=60000,
        active_complaints=0,
        is_san=True,
        court_admissions=["federal_high_court", "state_high_court", "court_of_appeal", "sharia"],
        legal_system="common_law",
        pro_bono_practice_areas=["contracts"],
    ),
    Lawyer(
        id="lw_003",
        full_name="Chioma Eze",
        state="Lagos",
        practice_areas=["family", "property"],
        years_called=6,
        nin_verified=True,
        nba_verified=True,
        bvn_verified=True,
        profile_completeness=79,
        completed_matters=12,
        rating=4.5,
        response_rate=90,
        avg_response_hours=5.0,
        repeat_client_rate=22,
        base_consult_fee_ngn=30000,
        active_complaints=0,
        court_admissions=["state_high_court", "customary"],
        legal_system="common_law",
        pro_bono_practice_areas=["family"],
    ),
    Lawyer(
        id="lw_004",
        full_name="Sadiq Bello",
        state="Lagos",
        practice_areas=["property", "land_dispute"],
        years_called=3,
        nin_verified=True,
        nba_verified=True,
        bvn_verified=False,
        profile_completeness=75,
        completed_matters=3,
        rating=4.4,
        response_rate=88,
        avg_response_hours=6.0,
        repeat_client_rate=10,
        base_consult_fee_ngn=20000,
        active_complaints=0,
    ),
    Lawyer(
        id="lw_005",
        full_name="Kemi Adegoke SAN",
        state="Lagos",
        practice_areas=["employment", "labour"],
        years_called=11,
        nin_verified=True,
        nba_verified=True,
        bvn_verified=True,
        profile_completeness=97,
        completed_matters=71,
        rating=4.9,
        response_rate=98,
        avg_response_hours=1.2,
        repeat_client_rate=52,
        base_consult_fee_ngn=70000,
        active_complaints=0,
        is_san=True,
        court_admissions=["federal_high_court", "state_high_court", "national_industrial", "court_of_appeal"],
        legal_system="common_law",
    ),
    Lawyer(
        id="lw_006",
        full_name="Kunle Martins",
        state="Lagos",
        practice_areas=["property", "contracts"],
        years_called=5,
        nin_verified=True,
        nba_verified=True,
        bvn_verified=True,
        profile_completeness=68,
        completed_matters=8,
        rating=4.2,
        response_rate=81,
        avg_response_hours=9.0,
        repeat_client_rate=14,
        base_consult_fee_ngn=25000,
        active_complaints=0,
    ),
    Lawyer(
        id="lw_007",
        full_name="Tosin Adeyemi",
        state="Port Harcourt",
        practice_areas=["oil_gas", "contracts"],
        years_called=9,
        nin_verified=True,
        nba_verified=True,
        bvn_verified=True,
        profile_completeness=86,
        completed_matters=29,
        rating=4.6,
        response_rate=91,
        avg_response_hours=4.2,
        repeat_client_rate=28,
        base_consult_fee_ngn=55000,
        active_complaints=0,
    ),
    Lawyer(
        id="lw_008",
        full_name="Blessing Nwosu",
        state="Lagos",
        practice_areas=["property", "tenancy"],
        years_called=2,
        nin_verified=True,
        nba_verified=True,
        bvn_verified=False,
        profile_completeness=73,
        completed_matters=1,
        rating=4.6,
        response_rate=86,
        avg_response_hours=7.5,
        repeat_client_rate=0,
        base_consult_fee_ngn=18000,
        active_complaints=0,
    ),
    Lawyer(
        id="lw_009",
        full_name="Henry Okafor",
        state="Lagos",
        practice_areas=["property", "land_dispute"],
        years_called=4,
        nin_verified=False,
        nba_verified=True,
        bvn_verified=False,
        profile_completeness=80,
        completed_matters=6,
        rating=4.1,
        response_rate=84,
        avg_response_hours=10.0,
        repeat_client_rate=12,
        base_consult_fee_ngn=20000,
        active_complaints=0,
    ),
    Lawyer(
        id="lw_010",
        full_name="Ngozi Umeh",
        state="Abuja",
        practice_areas=["family", "litigation"],
        years_called=13,
        nin_verified=True,
        nba_verified=True,
        bvn_verified=True,
        profile_completeness=95,
        completed_matters=48,
        rating=4.8,
        response_rate=95,
        avg_response_hours=2.1,
        repeat_client_rate=37,
        base_consult_fee_ngn=65000,
        active_complaints=0,
    ),
]
